name: nexmax_hrms
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  draggable_scrollbar: ^0.1.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  get: ^4.6.6
  http: ^1.1.0
  image_picker: ^1.0.4
  file_picker: ^8.0.6
  intl: ^0.19.0
  lottie: ^3.1.2
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  skeletonizer: ^1.4.1+1
  flutter_html: ^3.0.0-beta.2
  shimmer: ^3.0.0
  location: ^7.0.0
  flutter_barcode_scanner: ^2.0.0
  slide_to_act: ^2.0.2
  geocoding: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  month_year_picker: ^0.4.0+1
  font_awesome_flutter: ^10.7.0
  open_file: ^3.3.2
  pdf: ^3.10.1
  printing: ^5.13.1
  permission_handler: ^10.2.0
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.7
  firebase_auth: ^4.20.0
  pinput: ^2.2.7
  intl_phone_field: ^3.1.0
dev_dependencies:
  print_remover: ^1.0.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
